--
-- PostgreSQL database dump
--

-- Dumped from database version 10.18 (Ubuntu 10.18-0ubuntu0.18.04.1)
-- Dumped by pg_dump version 13.3

-- Started on 2021-08-13 17:39:29

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 196 (class 1259 OID 180385)
-- Name: departamento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.departamento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.departamento_id_seq OWNER TO postgres;

--
-- TOC entry 2958 (class 0 OID 0)
-- Dependencies: 196
-- Name: SEQUENCE departamento_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE public.departamento_id_seq IS 'DbWrench Autogenerated Sequence.';


SET default_tablespace = '';

--
-- TOC entry 201 (class 1259 OID 180395)
-- Name: departamento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departamento (
    id bigint DEFAULT nextval('public.departamento_id_seq'::regclass) NOT NULL,
    id_user_creacion bigint,
    id_user_actualizacion bigint,
    fecha_creacion timestamp without time zone,
    fecha_actualizacion timestamp without time zone,
    nombre character varying(100) NOT NULL,
    codigo character varying(100) NOT NULL
);


ALTER TABLE public.departamento OWNER TO postgres;

--
-- TOC entry 2959 (class 0 OID 0)
-- Dependencies: 201
-- Name: TABLE departamento; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.departamento IS 'Contiene la información de los departamentos de la empresa';


--
-- TOC entry 2960 (class 0 OID 0)
-- Dependencies: 201
-- Name: COLUMN departamento.id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.departamento.id IS 'Llave primaria';


--
-- TOC entry 2961 (class 0 OID 0)
-- Dependencies: 201
-- Name: COLUMN departamento.id_user_creacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.departamento.id_user_creacion IS 'Contiene el id del usuario que crea el registro';


--
-- TOC entry 2962 (class 0 OID 0)
-- Dependencies: 201
-- Name: COLUMN departamento.id_user_actualizacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.departamento.id_user_actualizacion IS 'Contiene el id del usuario que realiza la actualización del registro';


--
-- TOC entry 2963 (class 0 OID 0)
-- Dependencies: 201
-- Name: COLUMN departamento.fecha_creacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.departamento.fecha_creacion IS 'Contiene la fecha de creación del registro';


--
-- TOC entry 2964 (class 0 OID 0)
-- Dependencies: 201
-- Name: COLUMN departamento.fecha_actualizacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.departamento.fecha_actualizacion IS 'Contiene la fecha de la actualización';


--
-- TOC entry 2965 (class 0 OID 0)
-- Dependencies: 201
-- Name: COLUMN departamento.nombre; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.departamento.nombre IS 'Contiene el nombre del departamento';


--
-- TOC entry 2966 (class 0 OID 0)
-- Dependencies: 201
-- Name: COLUMN departamento.codigo; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.departamento.codigo IS 'Contiene el código del departamento';


--
-- TOC entry 197 (class 1259 OID 180387)
-- Name: empleado_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.empleado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.empleado_id_seq OWNER TO postgres;

--
-- TOC entry 2967 (class 0 OID 0)
-- Dependencies: 197
-- Name: SEQUENCE empleado_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE public.empleado_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 202 (class 1259 OID 180401)
-- Name: empleado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.empleado (
    id bigint DEFAULT nextval('public.empleado_id_seq'::regclass) NOT NULL,
    departamento_id bigint NOT NULL,
    persona_id bigint NOT NULL,
    fecha_ingreso date NOT NULL,
    id_user_creacion bigint,
    id_user_actualizacion bigint,
    fecha_creacion timestamp without time zone,
    fecha_actualizacion timestamp without time zone
);


ALTER TABLE public.empleado OWNER TO postgres;

--
-- TOC entry 2968 (class 0 OID 0)
-- Dependencies: 202
-- Name: TABLE empleado; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.empleado IS 'Contiene la información de los empleados';


--
-- TOC entry 2969 (class 0 OID 0)
-- Dependencies: 202
-- Name: COLUMN empleado.id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.empleado.id IS 'Llave primaria';


--
-- TOC entry 2970 (class 0 OID 0)
-- Dependencies: 202
-- Name: COLUMN empleado.departamento_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.empleado.departamento_id IS 'Llave primaria';


--
-- TOC entry 2971 (class 0 OID 0)
-- Dependencies: 202
-- Name: COLUMN empleado.persona_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.empleado.persona_id IS 'Llave primaria';


--
-- TOC entry 2972 (class 0 OID 0)
-- Dependencies: 202
-- Name: COLUMN empleado.fecha_ingreso; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.empleado.fecha_ingreso IS 'Contiene la fecha de ingreso del empleado';


--
-- TOC entry 2973 (class 0 OID 0)
-- Dependencies: 202
-- Name: COLUMN empleado.id_user_creacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.empleado.id_user_creacion IS 'Contiene el id del usuario que crea el registro';


--
-- TOC entry 2974 (class 0 OID 0)
-- Dependencies: 202
-- Name: COLUMN empleado.id_user_actualizacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.empleado.id_user_actualizacion IS 'Contiene el id del usuario que realiza la actualización del registro';


--
-- TOC entry 2975 (class 0 OID 0)
-- Dependencies: 202
-- Name: COLUMN empleado.fecha_creacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.empleado.fecha_creacion IS 'Contiene la fecha de creación del registro';


--
-- TOC entry 2976 (class 0 OID 0)
-- Dependencies: 202
-- Name: COLUMN empleado.fecha_actualizacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.empleado.fecha_actualizacion IS 'Contiene la fecha de la actualización';


--
-- TOC entry 208 (class 1259 OID 180466)
-- Name: encuesta_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.encuesta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.encuesta_id_seq OWNER TO postgres;

--
-- TOC entry 2977 (class 0 OID 0)
-- Dependencies: 208
-- Name: SEQUENCE encuesta_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE public.encuesta_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 209 (class 1259 OID 180468)
-- Name: encuesta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.encuesta (
    id bigint DEFAULT nextval('public.encuesta_id_seq'::regclass) NOT NULL,
    nombres character varying(150),
    marca_id bigint NOT NULL,
    email character varying(200) NOT NULL,
    id_user_creacion bigint,
    id_user_actualizacion bigint,
    fecha_creacion timestamp without time zone,
    fecha_actualizacion timestamp without time zone,
    apellidos character varying(150) NOT NULL
);


ALTER TABLE public.encuesta OWNER TO postgres;

--
-- TOC entry 2978 (class 0 OID 0)
-- Dependencies: 209
-- Name: TABLE encuesta; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.encuesta IS 'Contiene la información de las encuentas';


--
-- TOC entry 2979 (class 0 OID 0)
-- Dependencies: 209
-- Name: COLUMN encuesta.id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.encuesta.id IS 'Llave primaria';


--
-- TOC entry 2980 (class 0 OID 0)
-- Dependencies: 209
-- Name: COLUMN encuesta.nombres; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.encuesta.nombres IS 'Contiene el nombre de la persona';


--
-- TOC entry 2981 (class 0 OID 0)
-- Dependencies: 209
-- Name: COLUMN encuesta.marca_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.encuesta.marca_id IS 'Llave primaria';


--
-- TOC entry 2982 (class 0 OID 0)
-- Dependencies: 209
-- Name: COLUMN encuesta.email; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.encuesta.email IS 'Contiene el email de la persona';


--
-- TOC entry 2983 (class 0 OID 0)
-- Dependencies: 209
-- Name: COLUMN encuesta.id_user_creacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.encuesta.id_user_creacion IS 'Contiene el id del usuario que crea el registro';


--
-- TOC entry 2984 (class 0 OID 0)
-- Dependencies: 209
-- Name: COLUMN encuesta.id_user_actualizacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.encuesta.id_user_actualizacion IS 'Contiene el id del usuario que realiza la actualización del registro';


--
-- TOC entry 2985 (class 0 OID 0)
-- Dependencies: 209
-- Name: COLUMN encuesta.fecha_creacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.encuesta.fecha_creacion IS 'Contiene la fecha de creación del registro';


--
-- TOC entry 2986 (class 0 OID 0)
-- Dependencies: 209
-- Name: COLUMN encuesta.fecha_actualizacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.encuesta.fecha_actualizacion IS 'Contiene la fecha de la actualización';


--
-- TOC entry 2987 (class 0 OID 0)
-- Dependencies: 209
-- Name: COLUMN encuesta.apellidos; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.encuesta.apellidos IS 'Contiene el apellido';


--
-- TOC entry 206 (class 1259 OID 180458)
-- Name: marca_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.marca_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.marca_id_seq OWNER TO postgres;

--
-- TOC entry 2988 (class 0 OID 0)
-- Dependencies: 206
-- Name: SEQUENCE marca_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE public.marca_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 207 (class 1259 OID 180460)
-- Name: marca; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.marca (
    id bigint DEFAULT nextval('public.marca_id_seq'::regclass) NOT NULL,
    nombre character varying(100),
    id_user_creacion bigint,
    id_user_actualizacion bigint,
    fecha_creacion timestamp without time zone,
    fecha_actualizacion timestamp without time zone
);


ALTER TABLE public.marca OWNER TO postgres;

--
-- TOC entry 2989 (class 0 OID 0)
-- Dependencies: 207
-- Name: TABLE marca; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.marca IS 'Contiene las marca de los PC';


--
-- TOC entry 2990 (class 0 OID 0)
-- Dependencies: 207
-- Name: COLUMN marca.id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.marca.id IS 'Llave primaria';


--
-- TOC entry 2991 (class 0 OID 0)
-- Dependencies: 207
-- Name: COLUMN marca.nombre; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.marca.nombre IS 'Contiene el nombre';


--
-- TOC entry 2992 (class 0 OID 0)
-- Dependencies: 207
-- Name: COLUMN marca.id_user_creacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.marca.id_user_creacion IS 'Contiene el id del usuario que crea el registro';


--
-- TOC entry 2993 (class 0 OID 0)
-- Dependencies: 207
-- Name: COLUMN marca.id_user_actualizacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.marca.id_user_actualizacion IS 'Contiene el id del usuario que realiza la actualización del registro';


--
-- TOC entry 2994 (class 0 OID 0)
-- Dependencies: 207
-- Name: COLUMN marca.fecha_creacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.marca.fecha_creacion IS 'Contiene la fecha de creación del registro';


--
-- TOC entry 2995 (class 0 OID 0)
-- Dependencies: 207
-- Name: COLUMN marca.fecha_actualizacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.marca.fecha_actualizacion IS 'Contiene la fecha de la actualización';


--
-- TOC entry 198 (class 1259 OID 180389)
-- Name: persona_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.persona_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.persona_id_seq OWNER TO postgres;

--
-- TOC entry 2996 (class 0 OID 0)
-- Dependencies: 198
-- Name: SEQUENCE persona_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE public.persona_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 203 (class 1259 OID 180407)
-- Name: persona; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.persona (
    id bigint DEFAULT nextval('public.persona_id_seq'::regclass) NOT NULL,
    tipo_identificacion_id bigint NOT NULL,
    numero_identificacion bigint NOT NULL,
    nombres character varying(100) NOT NULL,
    apellidos character varying(100) NOT NULL,
    telefono bigint,
    direccion character varying(150),
    email character varying(150),
    id_user_creacion bigint,
    id_user_actualizacion bigint,
    fecha_creacion timestamp without time zone,
    fecha_actualizacion timestamp without time zone
);


ALTER TABLE public.persona OWNER TO postgres;

--
-- TOC entry 2997 (class 0 OID 0)
-- Dependencies: 203
-- Name: TABLE persona; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.persona IS 'Contiene la información de las personas';


--
-- TOC entry 2998 (class 0 OID 0)
-- Dependencies: 203
-- Name: COLUMN persona.id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.persona.id IS 'Llave primaria';


--
-- TOC entry 2999 (class 0 OID 0)
-- Dependencies: 203
-- Name: COLUMN persona.tipo_identificacion_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.persona.tipo_identificacion_id IS 'Llave primaria';


--
-- TOC entry 3000 (class 0 OID 0)
-- Dependencies: 203
-- Name: COLUMN persona.numero_identificacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.persona.numero_identificacion IS 'Contiene el número de identificación';


--
-- TOC entry 3001 (class 0 OID 0)
-- Dependencies: 203
-- Name: COLUMN persona.nombres; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.persona.nombres IS 'Contiene los nombres de la persona';


--
-- TOC entry 3002 (class 0 OID 0)
-- Dependencies: 203
-- Name: COLUMN persona.apellidos; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.persona.apellidos IS 'Contiene los apellidos de la persona';


--
-- TOC entry 3003 (class 0 OID 0)
-- Dependencies: 203
-- Name: COLUMN persona.telefono; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.persona.telefono IS 'Contiene el número teléfonico de la persona';


--
-- TOC entry 3004 (class 0 OID 0)
-- Dependencies: 203
-- Name: COLUMN persona.direccion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.persona.direccion IS 'Contiene la dirección de la persona';


--
-- TOC entry 3005 (class 0 OID 0)
-- Dependencies: 203
-- Name: COLUMN persona.email; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.persona.email IS 'Contiene el email de la persona';


--
-- TOC entry 3006 (class 0 OID 0)
-- Dependencies: 203
-- Name: COLUMN persona.id_user_creacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.persona.id_user_creacion IS 'Contiene el id del usuario que crea el registro';


--
-- TOC entry 3007 (class 0 OID 0)
-- Dependencies: 203
-- Name: COLUMN persona.id_user_actualizacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.persona.id_user_actualizacion IS 'Contiene el id del usuario que realiza la actualización del registro';


--
-- TOC entry 3008 (class 0 OID 0)
-- Dependencies: 203
-- Name: COLUMN persona.fecha_creacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.persona.fecha_creacion IS 'Contiene la fecha de creación del registro';


--
-- TOC entry 3009 (class 0 OID 0)
-- Dependencies: 203
-- Name: COLUMN persona.fecha_actualizacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.persona.fecha_actualizacion IS 'Contiene la fecha de la actualización';


--
-- TOC entry 199 (class 1259 OID 180391)
-- Name: tipo_identificacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tipo_identificacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.tipo_identificacion_id_seq OWNER TO postgres;

--
-- TOC entry 3010 (class 0 OID 0)
-- Dependencies: 199
-- Name: SEQUENCE tipo_identificacion_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE public.tipo_identificacion_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 204 (class 1259 OID 180416)
-- Name: tipo_identificacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_identificacion (
    id bigint DEFAULT nextval('public.tipo_identificacion_id_seq'::regclass) NOT NULL,
    codigo character varying(50) NOT NULL,
    nombre character varying(100),
    id_user_creacion bigint,
    id_user_actualizacion bigint,
    fecha_creacion timestamp without time zone,
    fecha_actualizacion timestamp without time zone
);


ALTER TABLE public.tipo_identificacion OWNER TO postgres;

--
-- TOC entry 3011 (class 0 OID 0)
-- Dependencies: 204
-- Name: TABLE tipo_identificacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.tipo_identificacion IS 'Contiene los tipos de identificación';


--
-- TOC entry 3012 (class 0 OID 0)
-- Dependencies: 204
-- Name: COLUMN tipo_identificacion.id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tipo_identificacion.id IS 'Llave primaria';


--
-- TOC entry 3013 (class 0 OID 0)
-- Dependencies: 204
-- Name: COLUMN tipo_identificacion.codigo; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tipo_identificacion.codigo IS 'Contiene el codigo unico del tipo de identificación';


--
-- TOC entry 3014 (class 0 OID 0)
-- Dependencies: 204
-- Name: COLUMN tipo_identificacion.nombre; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tipo_identificacion.nombre IS 'Contiene el nombre';


--
-- TOC entry 3015 (class 0 OID 0)
-- Dependencies: 204
-- Name: COLUMN tipo_identificacion.id_user_creacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tipo_identificacion.id_user_creacion IS 'Contiene el id del usuario que crea el registro';


--
-- TOC entry 3016 (class 0 OID 0)
-- Dependencies: 204
-- Name: COLUMN tipo_identificacion.id_user_actualizacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tipo_identificacion.id_user_actualizacion IS 'Contiene el id del usuario que realiza la actualización del registro';


--
-- TOC entry 3017 (class 0 OID 0)
-- Dependencies: 204
-- Name: COLUMN tipo_identificacion.fecha_creacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tipo_identificacion.fecha_creacion IS 'Contiene la fecha de creación del registro';


--
-- TOC entry 3018 (class 0 OID 0)
-- Dependencies: 204
-- Name: COLUMN tipo_identificacion.fecha_actualizacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tipo_identificacion.fecha_actualizacion IS 'Contiene la fecha de la actualización';


--
-- TOC entry 200 (class 1259 OID 180393)
-- Name: tramite_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tramite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.tramite_id_seq OWNER TO postgres;

--
-- TOC entry 3019 (class 0 OID 0)
-- Dependencies: 200
-- Name: SEQUENCE tramite_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE public.tramite_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 205 (class 1259 OID 180423)
-- Name: tramite; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tramite (
    id bigint DEFAULT nextval('public.tramite_id_seq'::regclass) NOT NULL,
    numero bigint NOT NULL,
    ano integer NOT NULL,
    nombre character varying(200) NOT NULL,
    descripcion character varying(600),
    empleado_id bigint,
    persona_id bigint NOT NULL,
    id_user_creacion bigint NOT NULL,
    id_user_actualizacion bigint,
    fecha_creacion timestamp without time zone,
    fecha_actualizacion timestamp without time zone NOT NULL
);


ALTER TABLE public.tramite OWNER TO postgres;

--
-- TOC entry 3020 (class 0 OID 0)
-- Dependencies: 205
-- Name: TABLE tramite; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.tramite IS 'Contiene la información de los tramites de las personas';


--
-- TOC entry 3021 (class 0 OID 0)
-- Dependencies: 205
-- Name: COLUMN tramite.id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tramite.id IS 'Llave primaria';


--
-- TOC entry 3022 (class 0 OID 0)
-- Dependencies: 205
-- Name: COLUMN tramite.numero; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tramite.numero IS 'Número del tramite';


--
-- TOC entry 3023 (class 0 OID 0)
-- Dependencies: 205
-- Name: COLUMN tramite.ano; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tramite.ano IS 'Número del año del tramite';


--
-- TOC entry 3024 (class 0 OID 0)
-- Dependencies: 205
-- Name: COLUMN tramite.nombre; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tramite.nombre IS 'Nombre del tramite';


--
-- TOC entry 3025 (class 0 OID 0)
-- Dependencies: 205
-- Name: COLUMN tramite.descripcion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tramite.descripcion IS 'Descripción del tramite';


--
-- TOC entry 3026 (class 0 OID 0)
-- Dependencies: 205
-- Name: COLUMN tramite.empleado_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tramite.empleado_id IS 'Empleado que recibe el tramite';


--
-- TOC entry 3027 (class 0 OID 0)
-- Dependencies: 205
-- Name: COLUMN tramite.persona_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tramite.persona_id IS 'Persona que radica el tramite';


--
-- TOC entry 3028 (class 0 OID 0)
-- Dependencies: 205
-- Name: COLUMN tramite.id_user_creacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tramite.id_user_creacion IS 'Contiene el id del usuario que crea el registro';


--
-- TOC entry 3029 (class 0 OID 0)
-- Dependencies: 205
-- Name: COLUMN tramite.id_user_actualizacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tramite.id_user_actualizacion IS 'Contiene el id del usuario que realiza la actualización del registro';


--
-- TOC entry 3030 (class 0 OID 0)
-- Dependencies: 205
-- Name: COLUMN tramite.fecha_creacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tramite.fecha_creacion IS 'Contiene la fecha de creación del registro';


--
-- TOC entry 3031 (class 0 OID 0)
-- Dependencies: 205
-- Name: COLUMN tramite.fecha_actualizacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tramite.fecha_actualizacion IS 'Contiene la fecha de la actualización';


--
-- TOC entry 2944 (class 0 OID 180395)
-- Dependencies: 201
-- Data for Name: departamento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.departamento (id, id_user_creacion, id_user_actualizacion, fecha_creacion, fecha_actualizacion, nombre, codigo) FROM stdin;
2	\N	\N	\N	\N	Cartera	CAR
3	\N	\N	\N	\N	Soporte	SOP
\.


--
-- TOC entry 2945 (class 0 OID 180401)
-- Dependencies: 202
-- Data for Name: empleado; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.empleado (id, departamento_id, persona_id, fecha_ingreso, id_user_creacion, id_user_actualizacion, fecha_creacion, fecha_actualizacion) FROM stdin;
2	2	2	2021-08-13	\N	\N	\N	\N
\.


--
-- TOC entry 2952 (class 0 OID 180468)
-- Dependencies: 209
-- Data for Name: encuesta; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.encuesta (id, nombres, marca_id, email, id_user_creacion, id_user_actualizacion, fecha_creacion, fecha_actualizacion, apellidos) FROM stdin;
1	Jonathan	4	ing.jonathan_arroyo@hotmail.com	\N	\N	2021-08-13 17:29:11.555	\N	Reina
\.


--
-- TOC entry 2950 (class 0 OID 180460)
-- Dependencies: 207
-- Data for Name: marca; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.marca (id, nombre, id_user_creacion, id_user_actualizacion, fecha_creacion, fecha_actualizacion) FROM stdin;
2	Lenovo	\N	\N	\N	\N
3	HP	\N	\N	\N	\N
4	Dell	\N	\N	\N	\N
\.


--
-- TOC entry 2946 (class 0 OID 180407)
-- Dependencies: 203
-- Data for Name: persona; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.persona (id, tipo_identificacion_id, numero_identificacion, nombres, apellidos, telefono, direccion, email, id_user_creacion, id_user_actualizacion, fecha_creacion, fecha_actualizacion) FROM stdin;
2	2	1045671097	Jonathan	Arroyo Reina	3215173946	CALLE 112 # 42 - 93	ing.jonathan_arroyo@hotmail.com	\N	\N	\N	\N
\.


--
-- TOC entry 2947 (class 0 OID 180416)
-- Dependencies: 204
-- Data for Name: tipo_identificacion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipo_identificacion (id, codigo, nombre, id_user_creacion, id_user_actualizacion, fecha_creacion, fecha_actualizacion) FROM stdin;
3	TI	Tarjeta de Identidad	\N	\N	\N	\N
2	CC	Cédula de Ciudadanía	\N	\N	\N	\N
\.


--
-- TOC entry 2948 (class 0 OID 180423)
-- Dependencies: 205
-- Data for Name: tramite; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tramite (id, numero, ano, nombre, descripcion, empleado_id, persona_id, id_user_creacion, id_user_actualizacion, fecha_creacion, fecha_actualizacion) FROM stdin;
\.


--
-- TOC entry 3032 (class 0 OID 0)
-- Dependencies: 196
-- Name: departamento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.departamento_id_seq', 3, true);


--
-- TOC entry 3033 (class 0 OID 0)
-- Dependencies: 197
-- Name: empleado_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.empleado_id_seq', 2, true);


--
-- TOC entry 3034 (class 0 OID 0)
-- Dependencies: 208
-- Name: encuesta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.encuesta_id_seq', 1, true);


--
-- TOC entry 3035 (class 0 OID 0)
-- Dependencies: 206
-- Name: marca_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.marca_id_seq', 4, true);


--
-- TOC entry 3036 (class 0 OID 0)
-- Dependencies: 198
-- Name: persona_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.persona_id_seq', 2, true);


--
-- TOC entry 3037 (class 0 OID 0)
-- Dependencies: 199
-- Name: tipo_identificacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipo_identificacion_id_seq', 3, true);


--
-- TOC entry 3038 (class 0 OID 0)
-- Dependencies: 200
-- Name: tramite_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tramite_id_seq', 1, false);


--
-- TOC entry 2797 (class 2606 OID 180400)
-- Name: departamento pkdepartamento; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departamento
    ADD CONSTRAINT pkdepartamento PRIMARY KEY (id);


--
-- TOC entry 2799 (class 2606 OID 180406)
-- Name: empleado pkempleado; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empleado
    ADD CONSTRAINT pkempleado PRIMARY KEY (id);


--
-- TOC entry 2811 (class 2606 OID 180473)
-- Name: encuesta pkencuesta; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.encuesta
    ADD CONSTRAINT pkencuesta PRIMARY KEY (id);


--
-- TOC entry 2809 (class 2606 OID 180465)
-- Name: marca pkmarca; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marca
    ADD CONSTRAINT pkmarca PRIMARY KEY (id);


--
-- TOC entry 2802 (class 2606 OID 180415)
-- Name: persona pkpersona; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT pkpersona PRIMARY KEY (id);


--
-- TOC entry 2804 (class 2606 OID 180421)
-- Name: tipo_identificacion pktipo_identificacion; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_identificacion
    ADD CONSTRAINT pktipo_identificacion PRIMARY KEY (id);


--
-- TOC entry 2807 (class 2606 OID 180431)
-- Name: tramite pktramite; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tramite
    ADD CONSTRAINT pktramite PRIMARY KEY (id);


--
-- TOC entry 2800 (class 1259 OID 180457)
-- Name: persona_tipo_ide_num_ide_Idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "persona_tipo_ide_num_ide_Idx" ON public.persona USING btree (tipo_identificacion_id, numero_identificacion);


--
-- TOC entry 2805 (class 1259 OID 180422)
-- Name: tipo_identificacion_codigo_Idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "tipo_identificacion_codigo_Idx" ON public.tipo_identificacion USING btree (codigo);


--
-- TOC entry 2812 (class 2606 OID 180432)
-- Name: empleado fk_empleado_departamento; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empleado
    ADD CONSTRAINT fk_empleado_departamento FOREIGN KEY (departamento_id) REFERENCES public.departamento(id);


--
-- TOC entry 2813 (class 2606 OID 180437)
-- Name: empleado fk_empleado_persona; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empleado
    ADD CONSTRAINT fk_empleado_persona FOREIGN KEY (persona_id) REFERENCES public.persona(id);


--
-- TOC entry 2817 (class 2606 OID 180474)
-- Name: encuesta fk_encuesta_marca; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.encuesta
    ADD CONSTRAINT fk_encuesta_marca FOREIGN KEY (marca_id) REFERENCES public.marca(id);


--
-- TOC entry 2814 (class 2606 OID 180442)
-- Name: persona fk_persona_tipo_identificacion; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT fk_persona_tipo_identificacion FOREIGN KEY (tipo_identificacion_id) REFERENCES public.tipo_identificacion(id);


--
-- TOC entry 2815 (class 2606 OID 180447)
-- Name: tramite fk_tramite_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tramite
    ADD CONSTRAINT fk_tramite_empleado FOREIGN KEY (empleado_id) REFERENCES public.empleado(id);


--
-- TOC entry 2816 (class 2606 OID 180452)
-- Name: tramite fk_tramite_persona; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tramite
    ADD CONSTRAINT fk_tramite_persona FOREIGN KEY (persona_id) REFERENCES public.persona(id);


-- Completed on 2021-08-13 17:39:30

--
-- PostgreSQL database dump complete
--

